code/final_proj_blog/blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view(), name='post_search'),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('create_post/', views.PostCreate.as_view(), name='post_create'),  # create_post에서 PostCreate로 변경
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('accounts/', include('allauth.urls')),
    path('', views.PostList.as_view(), name='post_list'),
    path('generate_image/', views.generate_image, name='generate_image'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/final_proj_blog/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile_update/', views.profile_update, name='profile_update'),  # 추가된 URL
    path('change_password/', views.change_password, name='change_password'),  # 비밀번호 변경 경로
    path('delete_account/', views.delete_account, name='delete_account'),  # 회원 탈퇴 경로 추가

]

code/final_proj_blog/final_proj_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('common/', include('common.urls')),
    path('today_word/', include('today_word.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('news/', include('news.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

code/final_proj_blog/common/models.py
from django.db import models

# Create your models here.

code/final_proj_blog/blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = False  # "content *" 표시 없애기.

    class Meta:
        model = Comment
        fields = ('content',)

code/final_proj_blog/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

class UserUpdateForm(UserChangeForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "email")  # 수정 가능한 필드 설정

code/final_proj_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from .models import Post, Tag, Comment, News, Subject
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from .forms import CommentForm
from django.utils import timezone
from django.utils.text import slugify
from .easystory import (
    initialize_rag_system,
    generate_answer,
    generate_debug_output,
    generate_response
)
from django.http import JsonResponse

from django.conf import settings
from django.http import JsonResponse
from .dalle import save_gen_img, OpenAI, BadRequestError
import json
import os
from dotenv import load_dotenv
from django.core.files import File
from urllib.request import urlopen
from tempfile import NamedTemporaryFile

load_dotenv()

# RAG 시스템 초기화
hybrid_retriever, tokenizer, model, llm_chain = initialize_rag_system()

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        # 오늘 날짜의 뉴스 필터링
        today = timezone.now().date()
        today_news = News.objects.filter(created_at__date=today)
        # 템플릿에 전달
        context['today_news'] = today_news
        context['comment_form'] = CommentForm
        return context
    
class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        # 오늘 날짜의 뉴스 필터링
        today = timezone.now().date()
        today_news = News.objects.filter(created_at__date=today)
        # 템플릿에 전달
        context['today_news'] = today_news
        context['comment_form'] = CommentForm
        return context

    



def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q}'
        return context


def generate_unique_slug(name):
    slug = slugify(name, allow_unicode=True)
    unique_slug = slug
    number = 1
    while Tag.objects.filter(slug=unique_slug).exists():
        unique_slug = f"{slug}-{number}"
        number += 1
    return unique_slug

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image']
    template_name = 'blog/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response



class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image']
    template_name = 'blog/create_new_post.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user

            # hidden input에서 이미지 URL 가져오기
            generated_image_url = self.request.POST.get('generated_image_url')
            if generated_image_url:
                # URL에서 이미지를 열어 임시 파일로 저장한 후 head_image에 첨부
                img_temp = NamedTemporaryFile(delete=True)
                img_temp.write(urlopen(generated_image_url).read())
                img_temp.flush()
                # 파일 이름을 지정하여 저장 (경로를 제거하고 파일명만 사용)
                file_name = os.path.basename(generated_image_url)
                form.instance.head_image.save(file_name, File(img_temp), save=False)

            response = super(PostCreate, self).form_valid(form)

            query = self.request.session.get('query')

            # Subject 테이블 업데이트
            title_instance = Subject.objects.filter(title=query).first()
            if title_instance:
                title_instance.use_yn = True
                title_instance.save()

            # 태그 추가
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip().replace(',', ';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    existing_tag = Tag.objects.filter(name=t).first()
                    if existing_tag:
                        tag = existing_tag
                    else:
                        tag = Tag(name=t)
                        tag.slug = generate_unique_slug(t)  # 고유 슬러그 생성 함수 사용
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use_yn=False인 질문 중 랜덤 선택
        query = Subject.objects.filter(category='post', use_yn=False).order_by('?').values('title').first()['title']
        context['title'] = query
        self.request.session['query'] = query

        if query:
            unique_documents, reranked_documents = generate_answer(query, hybrid_retriever, tokenizer, model)
            debug_output = generate_debug_output(unique_documents, reranked_documents)
            response = generate_response(query, reranked_documents, llm_chain)
            context['response'] = response
            context['debug_output'] = debug_output
        return context

    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and 'query' in request.GET:
            query = self.request.session.get('query')
            unique_documents, reranked_documents = generate_answer(query, hybrid_retriever, tokenizer, model)
            debug_output = generate_debug_output(unique_documents, reranked_documents)
            response = generate_response(query, reranked_documents, llm_chain)
            return JsonResponse({
                "response": response,
                "debug_output": debug_output
            })
        return super().get(request, *args, **kwargs)
    

def generate_image(request):
    if request.method == "POST":
        data = json.loads(request.body)
        txt_response = data.get("txt_response", "")
        client = OpenAI(api_key=os.getenv("OPENAI_KEY"))

        try:
            filename = save_gen_img(client, txt_response)
            file_url = request.build_absolute_uri(os.path.join(settings.MEDIA_URL, 'generated_images', filename))
        except BadRequestError:
            filename = save_gen_img(client, "시장 경제 활동")
            file_url = request.build_absolute_uri(os.path.join(settings.MEDIA_URL, 'generated_images', filename))

        return JsonResponse({"filename": filename, "file_url": file_url})    

code/final_proj_blog/common/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from common.forms import UserForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

def logout_view(request):
    logout(request)
    return redirect('/')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


@login_required
def profile_update(request):
    form = UserUpdateForm(request.POST or None, instance=request.user)
    if request.method == 'POST' and form.is_valid():
        form.save()
        messages.success(request, '회원 정보가 수정되었습니다.')
        return redirect('/')  # 랜딩 페이지로 리다이렉트
    return render(request, 'common/profile_update.html', {
        'form': form,
    })
@login_required
def change_password(request):
    password_form = PasswordChangeForm(request.user, request.POST or None)
    if request.method == 'POST' and password_form.is_valid():
        user = password_form.save()
        update_session_auth_hash(request, user)
        messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
        return redirect('/')
    return render(request, 'common/change_password.html', {
        'password_form': password_form,
    })
@login_required
def delete_account(request):
    if request.method == "POST":
        user = request.user
        user.is_active = False  # 사용자를 비활성화
        user.save()
        messages.success(request, "회원 탈퇴가 완료되었습니다.")
        logout(request)  # 로그아웃 처리
        return redirect('/')  # 홈 페이지로 리다이렉트
    return render(request, 'common/delete_account.html')

code/final_proj_blog/blog/templates/common/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>SKN AI Camp</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

code/final_proj_blog/blog/templates/common/change_password.html
<!-- common/change_password.html -->
{% extends "common/base.html" %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-secondary text-white">
                    <h3>비밀번호 변경</h3>
                </div>
                <div class="card-body p-4">
                    <form method="post" action="{% url 'common:change_password' %}">
                        {% csrf_token %}
                        {{ password_form.as_p }}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-secondary btn-block">비밀번호 변경</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

code/final_proj_blog/blog/templates/common/delete_account.html
<!-- common/delete_account.html -->
{% extends "common/base.html" %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-danger text-white">
                    <h3>회원 탈퇴</h3>
                </div>
                <div class="card-body p-4">
                    <p class="text-center">정말로 탈퇴하시겠습니까?</p>
                    <form method="post" action="{% url 'common:delete_account' %}">
                        {% csrf_token %}
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-danger btn-block">탈퇴하기</button>
                        </div>
                    </form>
                    <div class="mt-3 text-center">
                        <a href="{% url 'common:profile_update' %}" class="btn btn-link">취소</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

code/final_proj_blog/blog/templates/common/login.html
{% extends "common/base.html" %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-secondary text-white">
                    <h3>로그인</h3>
                </div>
                <div class="card-body p-4">
                    <form method="post" action="{% url 'common:login' %}">
                        {% csrf_token %}
                        {% include "form_errors.html" %}

                        <div class="mb-3">
                            <label for="username" class="form-label">사용자 ID</label>
                            <input type="text" class="form-control" name="username" id="username"
                                   placeholder="아이디를 입력하세요"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="password" class="form-label">비밀번호</label>
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="비밀번호를 입력하세요"
                                   value="{{ form.password.value|default_if_none:'' }}">
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-secondary btn-block">로그인</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <small class="text-muted">
                        <a href="#">비밀번호를 잊으셨나요?</a><br>
                        <a href="{% url 'common:signup' %}">회원가입</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

code/final_proj_blog/blog/templates/common/profile_update.html
<!-- common/profile_update.html -->
{% extends "common/base.html" %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-secondary text-white">
                    <h3>회원 정보 수정</h3>
                </div>
                <div class="card-body p-4">
                    <form method="post" action="{% url 'common:profile_update' %}">
                        {% csrf_token %}
                        {% include "form_errors.html" %}
                        <div class="mb-3">
                            <label for="username" class="form-label">사용자 이름</label>
                            <input type="text" class="form-control" name="username" id="username"
                                   placeholder="사용자 이름을 입력하세요"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">이메일</label>
                            <input type="email" class="form-control" name="email" id="email"
                                   placeholder="이메일을 입력하세요"
                                   value="{{ form.email.value|default_if_none:'' }}">
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-secondary btn-block">수정하기</button>
                        </div>
                    </form>
                    <div class="mt-3 text-center">
                        <!-- 비밀번호 변경 페이지로 이동하는 링크 추가 -->
                        <a href="{% url 'common:change_password' %}" class="btn btn-link">Set Password</a>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <small class="text-muted">
                        <a href="{% url 'common:logout' %}">로그아웃</a>
                        <a href="{% url 'common:delete_account' %}" class="text-danger">회원 탈퇴</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

code/final_proj_blog/blog/templates/common/signup.html
{% extends "common/base.html" %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-secondary text-white">
                    <h3>회원가입</h3>
                </div>
                <div class="card-body p-4">
                    <form method="post" action="{% url 'common:signup' %}">
                        {% csrf_token %}
                        {% include "form_errors.html" %}

                        <div class="mb-3">
                            <label for="username" class="form-label">사용자 이름</label>
                            <input type="text" class="form-control" name="username" id="username"
                                   placeholder="사용자 이름을 입력하세요"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="password1" class="form-label">비밀번호</label>
                            <input type="password" class="form-control" name="password1" id="password1"
                                   placeholder="비밀번호를 입력하세요"
                                   value="{{ form.password1.value|default_if_none:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="password2" class="form-label">비밀번호 확인</label>
                            <input type="password" class="form-control" name="password2" id="password2"
                                   placeholder="비밀번호를 다시 입력하세요"
                                   value="{{ form.password2.value|default_if_none:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label">이메일</label>
                            <input type="email" class="form-control" name="email" id="email"
                                   placeholder="이메일을 입력하세요"
                                   value="{{ form.email.value|default_if_none:'' }}">
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-secondary btn-block">생성하기</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <small class="text-muted">
                        이미 계정이 있으신가요? <a href="{% url 'common:login' %}">로그인</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}