code/final_proj_blog/blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view(), name='post_search'),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('create_post/', views.PostCreate.as_view(), name='post_create'),  # create_post에서 PostCreate로 변경
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('accounts/', include('allauth.urls')),
    path('', views.PostList.as_view(), name='post_list'),
    path('generate_image/', views.generate_image, name='generate_image'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/final_proj_blog/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile_update/', views.profile_update, name='profile_update'),  # 추가된 URL
    path('change_password/', views.change_password, name='change_password'),  # 비밀번호 변경 경로
    path('delete_account/', views.delete_account, name='delete_account'),  # 회원 탈퇴 경로 추가

]

code/final_proj_blog/final_proj_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('common/', include('common.urls')),
    path('today_word/', include('today_word.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('news/', include('news.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

code/final_proj_blog/blog/models.py
from xml.sax.handler import property_encoding

from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'

class Word_Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/today_word/tag/{self.slug}/'

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)

    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)

    @property
    def update_count(self):
        self.view_count += 1
        self.save()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'


class Word(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Word_Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/today_word/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)

class News(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Word_Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/news/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)


class Subject(models.Model):
    no = models.AutoField(primary_key=True, default=1)
    category = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    use_yn = models.BooleanField()


class RelatedWord(models.Model):
    no = models.IntegerField(primary_key=True)
    origin_num = models.IntegerField()
    origin_word = models.CharField(max_length=255)
    related_num = models.CharField(max_length=255, null=True)
    related_word = models.CharField(max_length=255)

code/final_proj_blog/blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = False  # "content *" 표시 없애기.

    class Meta:
        model = Comment
        fields = ('content',)

code/final_proj_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from .models import Post, Tag, Comment, News, Subject
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from .forms import CommentForm
from django.utils import timezone
from django.utils.text import slugify
from .easystory import (
    initialize_rag_system,
    generate_answer,
    generate_debug_output,
    generate_response
)
from django.http import JsonResponse

from django.conf import settings
from django.http import JsonResponse
from .dalle import save_gen_img, OpenAI, BadRequestError
import json
import os
from dotenv import load_dotenv
from django.core.files import File
from urllib.request import urlopen
from tempfile import NamedTemporaryFile

load_dotenv()

# RAG 시스템 초기화
hybrid_retriever, tokenizer, model, llm_chain = initialize_rag_system()

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        # 오늘 날짜의 뉴스 필터링
        today = timezone.now().date()
        today_news = News.objects.filter(created_at__date=today)
        # 템플릿에 전달
        context['today_news'] = today_news
        context['comment_form'] = CommentForm
        return context
    
class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        # 오늘 날짜의 뉴스 필터링
        today = timezone.now().date()
        today_news = News.objects.filter(created_at__date=today)
        # 템플릿에 전달
        context['today_news'] = today_news
        context['comment_form'] = CommentForm
        return context

    



def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q}'
        return context


def generate_unique_slug(name):
    slug = slugify(name, allow_unicode=True)
    unique_slug = slug
    number = 1
    while Tag.objects.filter(slug=unique_slug).exists():
        unique_slug = f"{slug}-{number}"
        number += 1
    return unique_slug

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image']
    template_name = 'blog/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response



class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image']
    template_name = 'blog/create_new_post.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user

            # hidden input에서 이미지 URL 가져오기
            generated_image_url = self.request.POST.get('generated_image_url')
            if generated_image_url:
                # URL에서 이미지를 열어 임시 파일로 저장한 후 head_image에 첨부
                img_temp = NamedTemporaryFile(delete=True)
                img_temp.write(urlopen(generated_image_url).read())
                img_temp.flush()
                # 파일 이름을 지정하여 저장 (경로를 제거하고 파일명만 사용)
                file_name = os.path.basename(generated_image_url)
                form.instance.head_image.save(file_name, File(img_temp), save=False)

            response = super(PostCreate, self).form_valid(form)

            query = self.request.session.get('query')

            # Subject 테이블 업데이트
            title_instance = Subject.objects.filter(title=query).first()
            if title_instance:
                title_instance.use_yn = True
                title_instance.save()

            # 태그 추가
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip().replace(',', ';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    existing_tag = Tag.objects.filter(name=t).first()
                    if existing_tag:
                        tag = existing_tag
                    else:
                        tag = Tag(name=t)
                        tag.slug = generate_unique_slug(t)  # 고유 슬러그 생성 함수 사용
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use_yn=False인 질문 중 랜덤 선택
        query = Subject.objects.filter(category='post', use_yn=False).order_by('?').values('title').first()['title']
        context['title'] = query
        self.request.session['query'] = query

        if query:
            unique_documents, reranked_documents = generate_answer(query, hybrid_retriever, tokenizer, model)
            debug_output = generate_debug_output(unique_documents, reranked_documents)
            response = generate_response(query, reranked_documents, llm_chain)
            context['response'] = response
            context['debug_output'] = debug_output
        return context

    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and 'query' in request.GET:
            query = self.request.session.get('query')
            unique_documents, reranked_documents = generate_answer(query, hybrid_retriever, tokenizer, model)
            debug_output = generate_debug_output(unique_documents, reranked_documents)
            response = generate_response(query, reranked_documents, llm_chain)
            return JsonResponse({
                "response": response,
                "debug_output": debug_output
            })
        return super().get(request, *args, **kwargs)
    

def generate_image(request):
    if request.method == "POST":
        data = json.loads(request.body)
        txt_response = data.get("txt_response", "")
        client = OpenAI(api_key=os.getenv("OPENAI_KEY"))

        try:
            filename = save_gen_img(client, txt_response)
            file_url = request.build_absolute_uri(os.path.join(settings.MEDIA_URL, 'generated_images', filename))
        except BadRequestError:
            filename = save_gen_img(client, "시장 경제 활동")
            file_url = request.build_absolute_uri(os.path.join(settings.MEDIA_URL, 'generated_images', filename))

        return JsonResponse({"filename": filename, "file_url": file_url})    

code/final_proj_blog/blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %}

{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-secondary float-right">Submit</button>
    </form>
{% endblock %}

code/final_proj_blog/blog/templates/blog/create_new_post.html
{% extends 'blog/base_full_width.html' %}

{% block main_area %}
<h2>Create New Post</h2>
<hr/>
<form method="post" action="{% url 'post_create' %}">
    {% csrf_token %}
    
    <div class="mb-3">
        <label for="id_title">Title*</label>
        <input type="text" id="id_title" name="title" class="form-control" required value="{{title}}" readonly>
        <button type="button" class="btn btn-primary mt-2" onclick="searchQuery()">Search</button>
    </div>

    <div class="mb-3">
        <label for="id_content">Content*</label>
        <textarea id="id_content" name="content" rows="10" class="form-control" required></textarea>
    </div>

    <div class="mb-3">
        <label for="id_tags_str">Tags</label>
        <input type="text" name="tags_str" id="id_tags_str" class="form-control" placeholder="콤마(,)로 구분하여 태그를 입력하세요.">
    </div>

    <!-- Image Upload Field -->
    <div class="mb-3">
        <label for="id_head_image">Head Image</label>
        <input type="file" name="head_image" id="id_head_image" class="form-control">
        <button type="button" class="btn btn-primary mt-2" onclick="generateImage()">Generate Image</button>
        <!-- 이미지 미리보기 영역 -->
        <div id="image-preview" class="mt-3">
            <p>No image generated yet.</p>
        </div>
        <!-- hidden input에 이미지 URL 저장 -->
        <input type="hidden" name="generated_image_url" id="generated_image_url">
    </div>

    <div class="mb-3">
        <label for="debug_output">Debug Output</label>
        <textarea id="debug_output" class="form-control" style="height: 300px; overflow-y: auto;" readonly></textarea>
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
</form>

<!-- 로딩 스피너 추가 -->
<div id="loading-spinner" style="display: none;">
    <div class="spinner-overlay">
        <div class="spinner"></div>
        <p class="loading-text">Loading...</p>
    </div>
</div>

<style>
    /* 로딩 오버레이와 스피너 스타일 */
    .spinner-overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000;
    }

    .spinner {
        width: 50px;
        height: 50px;
        border: 5px solid #f3f3f3;
        border-top: 5px solid #3498db;
        border-radius: 50%;
        animation: spin 1s linear infinite;
    }

    .loading-text {
        margin-top: 10px;
        color: #fff;
        font-size: 18px;
        text-align: center;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>

<script>
    function searchQuery() {
        const query = document.getElementById('id_title').value;
        if (!query) {
            alert("Please enter a query.");
            return;
        }

        // 로딩 스피너 표시
        document.getElementById('loading-spinner').style.display = 'flex';

        fetch("{% url 'post_create' %}?query=" + encodeURIComponent(query), {
            headers: { 'X-Requested-With': 'XMLHttpRequest' }
        })
        .then(response => response.json())
        .then(data => {
            document.getElementById('id_content').value = data.response || "No response";
            document.getElementById('debug_output').value = data.debug_output || "No debug output";
        })
        .catch(error => console.error('Error:', error))
        .finally(() => {
            // 로딩 스피너 숨기기
            document.getElementById('loading-spinner').style.display = 'none';
        });
    }

    function generateImage() {
        const txtResponse = document.getElementById('id_content').value;
        if (!txtResponse) {
            alert("Please enter content in the Content field.");
            return;
        }
        // 로딩 스피너 표시
        document.getElementById('loading-spinner').style.display = 'flex';
        fetch("{% url 'generate_image' %}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": "{{ csrf_token }}",
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: JSON.stringify({ txt_response: txtResponse })
        })
        .then(response => response.json())
        .then(data => {
            // 이미지 미리보기 업데이트
            const previewDiv = document.getElementById('image-preview');
            previewDiv.innerHTML = `<img src="${data.file_url}" alt="Generated Image" class="img-thumbnail" width="200">`;
            // hidden input에 이미지 URL 저장
            document.getElementById('generated_image_url').value = data.file_url;
        })
        .catch(error => console.error('Error:', error))
        .finally(() => {
            // 로딩 스피너 숨기기
            document.getElementById('loading-spinner').style.display = 'none';
        });
    }

</script>

{% endblock %}

code/final_proj_blog/blog/templates/blog/footer.html
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            SKN AI Camp Team_수빈
        </p>
    </div>
</footer>

code/final_proj_blog/blog/templates/blog/navbar.html
{% load socialaccount %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">SKN AI CAMP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About Me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/today_word/">Today Word</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/news/">News</a>
                </li>
            </ul>

            <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'common:profile_update' %}">Profile Update</a>
                            <a class="dropdown-item" href="{% url 'common:logout' %}">Sign Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Sign In</a>
                    </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="logInModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel"> <i class="fas fa-sign-in-alt"></i>&nbsp Sign In</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                       
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% url 'common:login' %}"><i class="far fa-envelope"></i>&nbsp&nbsp Sign in with UserID</a>
                    </div>
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% url 'common:signup' %}"><i class="far fa-envelope"></i>&nbsp&nbsp Sign Up with UserID</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

code/final_proj_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}

  <div id="post-area">

        {% if user.is_authenticated and user == post.author %}
            <div style="text-align: right;">
                <a href="/blog/update_post/{{ post.pk }}/" class="btn btn-secondary"><i class="fas fa-pen"></i>&nbsp;&nbsp;Edit Post</a>
            </div>
        {% endif %}

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
<!--        <p class="lead">-->
<!--          by-->
<!--          <a href="#">{{ post.author | upper }}</a>-->
<!--        </p>-->
        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ post.created_at }}</p>
        <hr>
        <!-- Preview Image -->
        {% if post.head_image %}
          <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image">
        {% else %}
          <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/800/200" alt="random_image">
        {% endif %}

        <hr>
        <!-- Post Content -->
        <p>{{ post.get_content_markdown | safe }}</p>

        {% if post.tags.exists %}
            <i class="fas fa-tags"></i>
            {% for tag in post.tags.all %}
                <a href="{% url 'post_search' tag.name %}"><span class="badge rounded-pill text-bg-light">{{ tag }}</span></a>
            {% endfor %}
            <br/>
            <br/>
        {% endif %}

        <hr>
  </div>

  <div id="comment-area">
        <!-- Comments Form -->
        <div class="card my-4">
          <style>
              #comment-form textarea {
              height: 100px; /* 원하는 높이로 조절 */
              }
          </style>
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            {% if user.is_authenticated %}
              <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                  {% csrf_token %}
                  <div class="form-group">
                      {{ comment_form | crispy }}
                  </div>
                  <button type="submit" class="btn btn-secondary">Submit</button>
              </form>
            {% else %}
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Sign in and leave a comment</a>
            {% endif %}
          </div>
        </div>

        {% if post.comment_set.exists %}
            {% for comment in post.comment_set.iterator %}
                <!-- Single Comment -->
                <div class="media mb-4" id="comment-{{ comment.pk }}">
                    <div class="media-body d-flex justify-content-between align-items-start">
                        <div>
                            <h5 class="mt-0">
                                {{ comment.author.username }}
                                &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                            </h5>
                            <p>{{ comment.content | linebreaks }}</p>
                            {% if comment.created_at != comment.modified_at %}
                            <p class="text-muted"><small>Updated: {{ comment.modified_at }}</small></p>
                            {% endif %}
                        </div>
                        {% if user.is_authenticated and comment.author == user %}
                        <div class="d-flex">
                        <a role="button"
                           class="btn btn-sm btn-secondary"
                           id="comment-{{ comment.pk }}-update-btn"
                           href="/blog/update_comment/{{ comment.pk }}/"
                            style="margin-right: 5px;">
                            edit
                        </a>
                        <a role="button"
                           class="btn btn-sm btn-danger"
                           id="comment-{{ comment.pk }}-delete-btn"
                           data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}"
                           href="#">
                            delete
                        </a>
                        </div>

                        <!-- Modal -->
                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <del>{{ comment | linebreaks }}</del>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <a role="button" class="btn btn-danger" href="/blog/delete_comment/{{ comment.pk }}/">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
  </div>
{% endblock %}